course = 'Python for Beginners'
print(len(course))
print(course.upper())
print(course.lower())
print(course)
print(course.find('P'))
print(course.find('p'))
print(course.find('Beginners'))
print(course.replace('Beginners' , 'Absolute Beginners'))
print(course.replace('P' , 'A'))
print(course.replace('A' , 'P'))
print('Python' in course)
print('in' in course)
print('at' in course)
print(course.title())